import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
})

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
})

export const metadata: Metadata = {
  title: "Campus Marketplace",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
